# Sesión 2: Manejo de datos con Pandas

## Índice

1. [¿Qué es una librería?](#qué-es-una-librería)
2. [Lectura de archivos Excel y CSV](#lectura-de-archivos-excel-y-csv)
   - [Manejo de rutas con Pathlib](#manejo-de-rutas-con-pathlib)
   - [Lectura de csv](#lectura-de-csv)
   - [Lectura de xlsx (diferentes hojas)](#lectura-de-xlsx-diferentes-hojas)
3. [Manejo de datos con Pandas](#manejo-de-datos-con-pandas)
   - [3.1. Inspección de DataFrames](#31-inspección-de-dataframes)
     - [Head](#head)
     - [Tail](#tail)
     - [Shape](#shape)
     - [Columns](#columns)
     - [Info](#info)
   - [3.2. Limpieza de DataFrames](#32-limpieza-de-dataframes)
     - [Drop](#drop)
     - [Rename](#rename)
     - [Replace](#replace)
     - [Fillna](#fillna)
     - [Iloc](#iloc)
   - [3.3. Manipulación de DataFrames](#33-manipulación-de-dataframes)
     - [3.3.1 Groupby](#331-groupby)
     - [3.3.2 Filtering Data](#332-filtering-data)
     - [3.3.3 Merge](#333-merge)
4. [Estadísticas descriptivas básicas](#estadísticas-descriptivas-básicas)
   - [4.1 Media](#41-media)
   - [4.2 Moda](#42-moda)
   - [4.3 Mediana](#43-mediana)
   - [4.4 Desviación estándar](#44-desviación-estándar)

#### En esta clase, vamos a trabajar con objetos, pero...¿qué es un objeto?

In [25]:
# Define aquí una función, un objeto y una clase

# función
def square(numero):
    print(numero * numero)

# clase
class Perro:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def alimentar(self, comida):
        print(f"El perro {self.nombre} fue alimentado con {comida}")

    def ladrar(self):
        print(f"El perro {self.nombre} ladró. Woof!")


# Objeto
mi_perro = Perro(nombre="firulais", edad="4")
mi_perro.ladrar()
mi_perro.alimentar("galleta")

El perro firulais ladró. Woof!
El perro firulais fue alimentado con galleta

## 1. ¿Qué es una librería?

Python es como una cocina básica: el espacio, el fuego, el fregadero. 

**¿Qué se puede hacer con lo básico?**
- Cocina: hervir agua, freír un huevo
- Python: cálculos básicos, manipulación de cadenas y caracteres.

**¿Qué pasa si ahora quiero ir más allá de lo básico?**

### Librería Estándar — los utensilios que vienen con la cocina

Las cocinas equipadas ya viene con utensilios básicos: cuchillos, ollas, una tabla de picar.

No obstante, para utilizarlos, debes **_importarlos_**: sacarlos de su cajón y ponerlos en la mesa.

Eso es la librería estándar. Viene con Python, siempre está ahí, pero debes importarlos primero si los quieres utilizar.

## Manejo de rutas con Pathlib

Normalmente, las rutas de archivos se escriben de manera absoluta, como cadenas:

In [5]:
finanzas_path = r"C:\Users\micha\OneDrive\Python\taller-intro-python-datos\sesiones\sesion_2\finanzas_personales.xlsx"

¿Cuál es el problema con esta forma de definir rutas?
- "Solo funciona en mi máquina"
- Se debe manipular la cadena manualmente para cambiar la ruta

Pathlib es una librería, parte de la librería estándar, para manejar rutas de manera intuitiva.

Pathlib no utiliza cadenas, sino un objeto "Path" que tiene sus propios métodos.

In [7]:
from pathlib import Path

# Siempre es bueno comenzar declarando la carpeta del script actual
CURRENT_DIR = Path.cwd()
print(CURRENT_DIR)
print(type(CURRENT_DIR))

c:\Users\micha\OneDrive\Python\taller-intro-python-datos\sesiones\sesion_2
<class 'pathlib.WindowsPath'>

Métodos del objeto "Path"

| Método | Definición |
|---|---|
| parent | Devuelve el directorio padre de la ruta. |
| name | Devuelve el nombre del archivo o carpeta final de la ruta, con extensión. |
| suffix | Devuelve la extensión del archivo, si tiene (ej: .txt). |
| mkdir() | Crea un nuevo directorio en la ruta especificada. |
| exists() | Verifica si la ruta (archivo o carpeta) existe. |
| is_file() | Retorna True si la ruta apunta a un archivo. |
| is_dir() | Retorna True si la ruta apunta a un directorio. |
| iterdir() | Itera sobre los elementos contenidos en un directorio. |
| rename() | Renombra o mueve el archivo/carpeta a una nueva ruta. |
| unlink() | Elimina el archivo al que apunta la ruta. |

In [ ]:
# Crear una nueva carpeta "data" dentro de la carpeta "sesión_2"
DATA_DIR = CURRENT_DIR / "data"

# Usamos mkdir
DATA_DIR.mkdir(exist_ok=True)
print(DATA_DIR.exists())

True

### Librerías Externas - los ingredientes que vas a comprar

Los utensilios ya estaban en la cocina. Pero si quieres cocinar ramen, necesitas fideos, caldo de hueso, huevo marinado. Eso no vino con el espacio — tienes que ir al supermercado primero.

Con las librerías externas hay dos pasos, no uno.

Primero vas al super (una sola vez):

`!pip install pandas`

Luego traes el ingrediente a la cocina cada vez que cocinas:

`import pandas as pd`

Si te saltas el primer paso e intentas importar directo, Python te dice que ese ingrediente no existe en tu cocina. No lo encuentra porque nunca lo compraste.

Igual que con los utensilios, no tiene sentido comprar todos los ingredientes del supermercado por si acaso. Compras lo que necesitas para el plato de hoy.

## 3. Manejo de datos con Pandas

### ¿Qué es Pandas?

Uno de los marcos más importantes para el análisis de datos en el ecosistema de Python es `pandas`, una librería diseñada para **importar, limpiar, transformar y analizar** datos tabulares (tablas).

Python no tiene librerías nativas para leer archivos excel, pero Pandas sí!

In [87]:
import pandas as pd
from pathlib import Path

# Comenzamos guardando la ruta del excel que vamos a leer
ROOT = Path.cwd()
finanzas_path = ROOT / "finanzas_personales.xlsx"

In [64]:
# Ahora utilizamos pd.read_excel
df = pd.read_excel(finanzas_path)
df

            Concepto            Monto
0   Ingresos Totales          3703.53
1     Gastos Totales          1056.25
2            Balance          2647.28
3                NaN              NaN
4                NaN              NaN
5         Categorías             Casa
6                NaN           Comida
7                NaN    Suscripciones
8                NaN       Transporte
9                NaN  Entretenimiento
10               NaN            Salud
11               NaN           Deudas
12               NaN             Amor
13               NaN            Otros

In [88]:
# Nos equivocamos. Necesitamos leer la hoja "gastos"
df = pd.read_excel(finanzas_path, sheet_name="Gastos")
df.head()

       Fecha  Descripción        Categoría   Monto Unnamed: 4
0 2026-04-01          NaN             Casa  1000.0        NaN
1 2026-04-02          NaN           Comida    45.0        NaN
2 2026-04-03          NaN           Comida    18.5        NaN
3 2026-04-05          NaN        Transport    12.0        NaN
4 2026-04-06          NaN  Entretenimiento    35.0       Amor

`pd.read_excel` y cualquier otra función de lectura de `pandas` nos devuelve un objeto `DataFrame`, que es básicamente una tabla con encabezados (headers).

### Inspección de DataFrames

Métodos de `DataFrame` para inspeccionar

| Método | Definición |
| --- | --- |
| head() | Muestra las primeras filas del DataFrame (por defecto 5). |
| tail() | Muestra las últimas filas del DataFrame (por defecto 5). |
| shape | Devuelve una tupla con el número de filas y columnas (filas, columnas). No es un método, es un atributo. |
| columns | Devuelve los nombres de las columnas del DataFrame. No es un método, es un atributo. |
| info() | Muestra un resumen del DataFrame: tipos de datos, valores nulos, memoria utilizada, etc. |

In [15]:
df.head()

       Fecha  Descripción        Categoría  Monto Unnamed: 4
0 2026-05-01          NaN       Transporte  10.50        NaN
1 2026-05-01          NaN  Entretenimiento  11.49        NaN
2 2026-05-02          NaN  Entretenimiento   4.60        NaN
3 2026-05-02          NaN            Otros   3.50        NaN
4 2026-05-02          NaN            Otros  18.60        NaN

In [16]:
df.tail()

        Fecha  Descripción   Categoría  Monto Unnamed: 4
42 2026-05-29          NaN      Comida   11.9        NaN
43 2026-05-29          NaN      Comida   13.5        NaN
44 2026-05-30          NaN  Transporte   19.2        NaN
45 2026-05-31          NaN  Transporte   11.0        NaN
46 2026-05-31          NaN  Transporte   14.0        NaN

In [ ]:
df.shape

        Fecha  Descripción   Categoría  Monto Unnamed: 4
42 2026-05-29          NaN      Comida   11.9        NaN
43 2026-05-29          NaN      Comida   13.5        NaN
44 2026-05-30          NaN  Transporte   19.2        NaN
45 2026-05-31          NaN  Transporte   11.0        NaN
46 2026-05-31          NaN  Transporte   14.0        NaN

In [89]:
# Reordenar a partir de los valores de una columna
df.columns

# Quiero mover las filas by la columna "monto"
print(df.sort_values(axis=0, by="Monto", ascending=False))

        Fecha  Descripción        Categoría   Monto Unnamed: 4
0  2026-04-01          NaN             Casa  1000.0        NaN
21 2026-05-01          NaN             Casa  1000.0        NaN
39 2026-06-01          NaN             Casa  1000.0        NaN
13 2026-04-24          NaN  Entretenimiento   150.0       Amor
53 2026-06-26          NaN  Entretenimiento   140.0       Amor
8  2026-04-14          NaN  Entretenimiento   140.0       Amor
45 2026-06-10          NaN  Entretenimiento   135.0       Amor
49 2026-06-18          NaN           Comida   120.0       Amor
18 2026-04-28          NaN           Comida   110.0        NaN
27 2026-05-10          NaN  Entretenimiento   110.0       Amor
50 2026-06-20          NaN  Entretenimiento   100.0       Amor
31 2026-05-18          NaN           Comida   100.0        NaN
35 2026-05-26          NaN  Entretenimiento    95.0       Amor
12 2026-04-22          NaN           Comida    95.0       Amor
14 2026-04-26          NaN            Otros    90.0        NaN
34 2026-05-24          NaN           Comida    90.0        NaN
52 2026-06-24          NaN           Comida    85.0        NaN
32 2026-05-20          NaN  Entretenimiento    80.0       Amor
5  2026-04-08          NaN           Comida    80.0       Amor
46 2026-06-12          NaN           Comida    70.0        NaN
11 2026-04-20          NaN            Otros    60.0       Amor
16 2026-04-26          NaN           Comida    60.0        NaN
54 2026-06-28          NaN            Otros    60.0        NaN
28 2026-05-12          NaN           Comida    60.0        NaN
48 2026-06-16          NaN            Otros    55.0       Amor
9  2026-04-16          NaN           Comida    55.0        NaN
40 2026-06-02          NaN           Comida    50.0        NaN
30 2026-05-16          NaN            Otros    50.0       Amor
15 2026-04-26          NaN  Entretenimiento    50.0       Amor
1  2026-04-02          NaN           Comida    45.0        NaN
36 2026-05-28          NaN            Otros    40.0        NaN
44 2026-06-08          NaN  Entretenimiento    40.0        NaN
22 2026-05-02          NaN           Comida    40.0        NaN
38 2026-05-23          NaN  Entretenimiento    40.0        NaN
4  2026-04-06          NaN  Entretenimiento    35.0       Amor
25 2026-05-06          NaN    Suscripciones    30.0        NaN
43 2026-06-06          NaN    Suscripciones    28.0        NaN
7  2026-04-12          NaN    Suscripciones    25.0        NaN
26 2026-05-10          NaN  Entretenimiento    25.0       Amor
17 2026-04-26          NaN       Transporte    25.0        NaN
55 2026-06-30          NaN       Transporte    25.0        NaN
10 2026-04-18          NaN       Transporte    22.0        NaN
23 2026-05-03          NaN           Comida    22.0        NaN
41 2026-06-03          NaN           Comida    20.0        NaN
37 2026-05-30          NaN       Transporte    20.0        NaN
51 2026-06-22          NaN       Transporte    20.0        NaN
2  2026-04-03          NaN           Comida    18.5        NaN
19 2026-04-30          NaN       Transporte    18.0        NaN
33 2026-05-22          NaN       Transporte    18.0        NaN
47 2026-06-14          NaN       Transporte    16.0        NaN
6  2026-04-10          NaN       Transporte    15.0        NaN
29 2026-05-14          NaN       Transporte    14.0        NaN
42 2026-06-05          NaN       Transporte    12.0        NaN
3  2026-04-05          NaN        Transport    12.0        NaN
24 2026-05-05          NaN       Transporte    10.0        NaN
20 2026-05-07          NaN            Otros     8.2        NaN

In [90]:
df["Categoría"].unique().tolist()

['Casa',
 'Comida',
 'Transport',
 'Entretenimiento',
 'Transporte',
 'Suscripciones',
 'Otros']

Ups, hay una categoría "Transport" que está mal escrita...

### Limpieza de DataFrames

Al hacer limpieza y manipulación, es buena práctica crear diferentes variables, como checkpoints, en lugar de reescribir la misma variable. Si la malogramos en el camino, debemos correr nuevamente la lectura de datos, y eso puede ser costoso.

Métodos de `DataFrame` para limpieza (3.2)

| Método | Definición |
| --- | --- |
| drop() | Elimina filas o columnas especificadas por etiqueta. Usa axis=0 para filas y axis=1 para columnas. |
| rename() | Cambia el nombre de columnas o índices, usando un diccionario {nombre_viejo: nombre_nuevo}. |
| replace() | Reemplaza valores específicos dentro del DataFrame por otros valores indicados. |
| fillna() | Rellena los valores nulos (NaN) con un valor especificado o un método (ej: media, valor fijo). |
| iloc() | Accede/modifica filas o columnas por posición entera (índice numérico). No acepta booleanos. |

Tareas:
- Borrar la columna "descripción"
- Renombrar "Unnamed: 4" a Amor
- Convertir la columna "Amor" a una variable dummy (0, 1)
- Corregir el error con la categoría "Transport"

In [91]:
# drop: Queremos ahora borrar la columna "descripción"
df_limpio = df.drop(columns=["Descripción"])
df_limpio.columns

Index(['Fecha', 'Categoría', 'Monto', 'Unnamed: 4'], dtype='str')

In [92]:
# rename: Queremos renombrar "Unammed: 4" a "Amor"
# Esto lo hacemos con un diccionario
df_limpio = df_limpio.rename(columns={"Unnamed: 4" : "Amor"})
df_limpio.columns

Index(['Fecha', 'Categoría', 'Monto', 'Amor'], dtype='str')

In [93]:
# replace: Queremos reemplazar "Amor" por una variable dummy: 
# 1 si es por amor, 0 si no lo es
print(df_limpio["Amor"].head(10))

0     NaN
1     NaN
2     NaN
3     NaN
4    Amor
5    Amor
6     NaN
7     NaN
8    Amor
9     NaN
Name: Amor, dtype: str

In [94]:
# Solo necesitamos reemplazar la columna "amor", así que eso será lo que reemplazamos
df_limpio["Amor"] = df_limpio["Amor"].replace({"Amor": 1})
print(df_limpio["Amor"].head(10))

0    NaN
1    NaN
2    NaN
3    NaN
4      1
5      1
6    NaN
7    NaN
8      1
9    NaN
Name: Amor, dtype: object

In [95]:
# fillna: Ahora a reemplazar NaN por 0
df_limpio["Amor"] = df_limpio["Amor"].fillna(0)
print(df_limpio.head(10))

       Fecha        Categoría   Monto Amor
0 2026-04-01             Casa  1000.0    0
1 2026-04-02           Comida    45.0    0
2 2026-04-03           Comida    18.5    0
3 2026-04-05        Transport    12.0    0
4 2026-04-06  Entretenimiento    35.0    1
5 2026-04-08           Comida    80.0    1
6 2026-04-10       Transporte    15.0    0
7 2026-04-12    Suscripciones    25.0    0
8 2026-04-14  Entretenimiento   140.0    1
9 2026-04-16           Comida    55.0    0

In [96]:
# iloc: Finalmente, a reemplazar "Transport" por "Transporte"
# Hay formas más eficientes de reemplazar esto, pero lo haremos con iloc para aprender a indexar
# Recuerda: (rows, columns)
print(df_limpio.iloc[3, 1])
df_limpio.iloc[3, 1] = "Transporte"
print(df_limpio.iloc[3, 1])

Transport
Transporte

### Manipulación de DataFrames

Conjunto de técnicas para transformar, limpiar, filtrar, agrupar y reorganizar datos en estructuras tabulares con el objetivo de facilitar su análisis.

Es como editar una hoja de Excel hasta que los datos nos cuenten una historia clara.

Buscamos responder a las siguientes preguntas del negocio:

- ¿En qué categoría he gastado más dinero? (ranking)
- ¿En qué categoría he gastado más dinero del PRESENTE MES?
- ¿En qué mes he gastado más dinero?
- ¿Porcentaje de gastos por amor vs gastos normales?
- ¿Me pasé del presupuesto en alguna categoría en este mes?

Métodos de `DataFrame` para manipulación (3.3)

| Método | Definición |
| --- | --- |
| groupby() | Agrupa filas según los valores de una o más columnas, permitiendo aplicar funciones de agregación (sum, mean, count, etc.). |
| filtering (indexación booleana) | Selecciona filas que cumplen una condición específica, usando una máscara booleana (ej: df[df['col'] > 5]). |
| merge() | Combina dos DataFrames en uno solo, uniendo filas según columnas o índices comunes (similar a un JOIN de SQL). |

In [105]:
# Vamos a crear una columna "mes" para que sea más sencillo manipular
df_limpio["Mes"] = df_limpio["Fecha"].dt.month
df_limpio.head()

       Fecha        Categoría   Monto Amor  Mes
0 2026-04-01             Casa  1000.0    0    4
1 2026-04-02           Comida    45.0    0    4
2 2026-04-03           Comida    18.5    0    4
3 2026-04-05       Transporte    12.0    0    4
4 2026-04-06  Entretenimiento    35.0    1    4

In [97]:
# Groupby: en qué categoría he gastado más dinero
# La primera variable es para agrupar, y la segunda es para calcular los números
monto_por_categoria = df_limpio.groupby("Categoría")["Monto"].sum().sort_values(ascending=False)
monto_por_categoria

Categoría
Casa               3000.0
Entretenimiento    1140.0
Comida             1120.5
Otros               363.2
Transporte          227.0
Suscripciones        83.0
Name: Monto, dtype: float64

In [106]:
# groupby: - ¿En qué mes he gastado más dinero? (ranking)
# La primera variable es para agrupar, y la segunda es para calcular los números
monto_por_mes = df_limpio.groupby(df_limpio["Mes"])["Monto"].sum().sort_values(ascending=False)
monto_por_mes

Mes
4    2105.5
6    1976.0
5    1852.2
Name: Monto, dtype: float64

In [107]:
# filtrando data: En qué categoría he gastado más dinero del PRESENTE MES
# La primera variable es para agrupar, y la segunda es para calcular los números
df_limpio_jun = df_limpio[df_limpio["Mes"] == 6]
monto_por_categoria_jun = df_limpio_jun.groupby("Categoría")["Monto"].sum().sort_values(ascending=False)
monto_por_categoria_jun

Categoría
Casa               1000.0
Entretenimiento     415.0
Comida              345.0
Otros               115.0
Transporte           73.0
Suscripciones        28.0
Name: Monto, dtype: float64

In [100]:
# Ahora añadimos el total
monto_por_categoria_jun["Total"] = monto_por_categoria_jun.sum()
monto_por_categoria_jun

Categoría
Casa               1000.0
Entretenimiento     415.0
Comida              345.0
Otros               115.0
Transporte           73.0
Suscripciones        28.0
Total              1976.0
Name: Monto, dtype: float64

In [101]:
# groupby: - ¿Cuánto gasto por amor comparado con lo que no?
# La primera variable es para agrupar, y la segunda es para calcular los números
monto_por_amor = df_limpio.groupby("Amor")["Monto"].sum()
porcentaje_por_amor = monto_por_amor / monto_por_amor.sum() * 100
porcentaje_por_amor

Amor
0    74.383606
1    25.616394
Name: Monto, dtype: float64

In [102]:
# merge: ¿Estoy sobre o bajo presupuesto?
# Leemos la tabla de presupuesto:
presupuesto = pd.read_excel(finanzas_path, sheet_name="Presupuesto")
presupuesto

         Categoría  Presupuesto
0       Transporte          300
1  Entretenimiento          500
2           Comida          500
3            Otros          150
4    Suscripciones           50
5             Casa         1000
6            Total         2000

In [114]:
# Solo para junio
df_junio = df_limpio[df_limpio["Mes"] == 6]

gasto_categoria_mes = (
    df_junio
    .groupby(["Mes", "Categoría"])["Monto"]
    .sum()
    .reset_index()
)
gasto_categoria_mes

   Mes        Categoría   Monto
0    6             Casa  1000.0
1    6           Comida   345.0
2    6  Entretenimiento   415.0
3    6            Otros   115.0
4    6    Suscripciones    28.0
5    6       Transporte    73.0

In [ ]:
# Hacemos merge a partir de categoría, esa será nuestra llave
comparacion = gasto_categoria_mes.merge(
    presupuesto,
    on="Categoría",
    how="left"
)
comparacion

   Mes        Categoría   Monto  Presupuesto
0    6             Casa  1000.0         1000
1    6           Comida   345.0          500
2    6  Entretenimiento   415.0          500
3    6            Otros   115.0          150
4    6    Suscripciones    28.0           50
5    6       Transporte    73.0          300

In [118]:
# Ahora verificamos que no nos hayamos pasado del presupuesto
comparacion_bool = comparacion["Monto"] > comparacion["Presupuesto"]
comparacion_bool

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

### Estadística descriptiva

Estadísticas descriptivas básicas

| Método | Definición |
| --- | --- |
| max() | Calcula el valor más alto de los valores numéricos de una columna o DataFrame. |
| mean() | Calcula la media (promedio) de los valores numéricos de una columna o DataFrame. |
| mode() | Calcula la moda, es decir, el valor que se repite con mayor frecuencia. |
| median() | Calcula la mediana, el valor central cuando los datos están ordenados. |
| std() | Calcula la desviación estándar, que mide la dispersión de los datos respecto a la media. |

Tareas:
- Max: ¿Cuál fue mi gasto más caro (sin contar casa)?
- Media: ¿Cuál es el gasto promedio cuando salgo por amor?
- Moda: ¿Cuál es la categoría en la que compro con mayor frecuencia?
- Mediana: ¿Cuál es la mediana de los gastos de entretenimiento?

In [ ]:
# Máximo: gasto más caro (sin contar casa)
df_limpio_sin_casa = df_limpio[df_limpio["Categoría"] != "Casa"]
max_gasto = df_limpio_sin_casa["Monto"].max()
max_gasto

np.float64(150.0)

In [124]:
# Para ver toda la fila completa
df_limpio_sin_casa.nlargest(1, "Monto")

        Fecha        Categoría  Monto Amor  Mes
13 2026-04-24  Entretenimiento  150.0    1    4

In [129]:
# Media: gasto amor
df_limpio_solo_amor = df_limpio[df_limpio["Amor"] == 1]
df_limpio_solo_amor

        Fecha        Categoría  Monto Amor  Mes
4  2026-04-06  Entretenimiento   35.0    1    4
5  2026-04-08           Comida   80.0    1    4
8  2026-04-14  Entretenimiento  140.0    1    4
11 2026-04-20            Otros   60.0    1    4
12 2026-04-22           Comida   95.0    1    4
13 2026-04-24  Entretenimiento  150.0    1    4
15 2026-04-26  Entretenimiento   50.0    1    4
26 2026-05-10  Entretenimiento   25.0    1    5
27 2026-05-10  Entretenimiento  110.0    1    5
30 2026-05-16            Otros   50.0    1    5
32 2026-05-20  Entretenimiento   80.0    1    5
35 2026-05-26  Entretenimiento   95.0    1    5
45 2026-06-10  Entretenimiento  135.0    1    6
48 2026-06-16            Otros   55.0    1    6
49 2026-06-18           Comida  120.0    1    6
50 2026-06-20  Entretenimiento  100.0    1    6
53 2026-06-26  Entretenimiento  140.0    1    6

In [130]:
df_limpio_solo_amor["Monto"].mean()

np.float64(89.41176470588235)

In [ ]:
# ¿Cuál es la categoría en la que compro con mayor frecuencia?
moda_categoria = df_limpio["Categoría"].mode()[0]

'Comida'

Más preguntas:

- ¿Cuántos gastos pequeños vs grandes? (Grandes > 50)